### PR TITLE
Change params in spacecraft NLN

### PR DESCRIPTION
**Pull request by mforets**

### CODE REVIEW

**Comment by lbenet** [comment]
The following is the way I am including the equation of motion for the space rendezvous problem.
```julia
const μ = 3.986e14 * 60^2
const r = 42164.0e3
const r2 = r^2
const mc = 500.0
const n2 = μ / r^3
const n = sqrt(n2)

const two_n = 2*n
const μ_r2 = μ/r2

const K₁ = [-28.8287 0.1005 -1449.9754 0.0046;
            -0.087 -33.2562 0.00462 -1451.5013]
const K₂ = [-288.0288 0.1312 -9614.9898 0.0;
            -0.1312 -288.0 0.0 -9614.9883]

const K₁mc = K₁/mc
const K₂mc = K₂/mc

function mymul!(v, A, x)
    for ind = 1:length(v)
        v[ind] = zero(x[1])
        for jind = 1:length(x)
            v[ind] += A[ind, jind] * x[jind]
        end
    end
    return nothing
end

# dynamics in the 'approaching' mode
@taylorize function spacecraft_approaching!(t, x, dx)
    x_1 = r + x[1]
    x_12 = x_1^2
    x_22 = x[2]^2
    rc = sqrt(x_12 + x_22)
    rc3 = rc^3
    μ_rc3 = μ / rc3

    uxy = Array{typeof(x[1])}(undef, size(K₁mc,1))
    mymul!(uxy, K₁mc, x)
    
    # x' = vx
    dx[1] = x[3]
    # y' = vy
    dx[2] = x[4]
    # vx' = n²x + 2n*vy + μ/(r^2) - μ/(rc^3)*(r+x) + ux/mc
    dx[3] = (n2*x[1] + two_n*x[4]) + ((μ_r2 - μ_rc3*x_1) + uxy[1])
    # vy' = n²y - 2n*vx - μ/(rc^3)y + uy/mc
    dx[4] = (n2*x[2] - two_n*x[3]) - (μ_rc3*x[2] - uxy[2])
    # t' = 1
    # dx[5] = one(t)

    return dx
end

# dynamics in the 'rendezvous attempt' mode
@taylorize function spacecraft_rendezvous_attempt!(t, x, dx)
    x_1 = r + x[1]
    x_12 = x_1^2
    x_22 = x[2]^2
    rc = sqrt(x_12 + x_22)
    rc3 = rc^3
    μ_rc3 = μ / rc3

    uxy = Array{typeof(x[1])}(undef, size(K₂mc,1))
    mymul!(uxy, K₂mc, x)

    # x' = vx
    dx[1] = x[3]
    # y' = vy
    dx[2] = x[4]
    # vx' = n²x + 2n*vy + μ/(r^2) - μ/(rc^3)*(r+x) + ux/mc
    dx[3] = (n2*x[1] + two_n*x[4]) + ((μ_r2 - μ_rc3*x_1) + uxy[1])
    # vy' = n²y - 2n*vx - μ/(rc^3)y + uy/mc
    dx[4] = (n2*x[2] - two_n*x[3]) - (μ_rc3*x[2] - uxy[2])
    # t' = 1
    # dx[5] = one(t)

    return dx
end

# dynamics in the 'aborting' mode
@taylorize function spacecraft_aborting!(t, x, dx)
    x_1 = r + x[1]
    x_12 = x_1^2
    x_22 = x[2]^2
    rc = sqrt(x_12 + x_22)
    rc3 = rc^3
    μ_rc3 = μ / rc3

    # x' = vx
    dx[1] = x[3]
    # y' = vy
    dx[2] = x[4]
    # vx' = n²x + 2n*vy + μ/(r^2) - μ/(rc^3)*(r+x)
    dx[3] = (n2*x[1] + two_n*x[4]) + (μ_r2 - μ_rc3*x_1)
    # vy' = n²y - 2n*vx - μ/(rc^3)y
    dx[4] = (n^2*x[2] - 2*n*x[3]) - μ/(rc^3)*x[2]
    dx[4] = (n2*x[2] - two_n*x[3]) - μ_rc3*x[2]

    # t' = 1
    # dx[5] = one(t)
    
    return dx
end
```

The parameters that I am using now are `orderQ = 2`, `orderT = 10`, and `abs_tolerance = 1.0e-28`. With those, and `max_steps=5000`, I am able to validate up to time `t=54.24`, and stopping there due to "maximum number of steps reached".

It is rather slow.

**Comment by mforets** [comment]
Hmm it could be that it's slow because we don't compute the intersection with the invariant in the continuous post.

**Comment by lbenet** [comment]
i was referring directly to the time of the integration; maybe those are not the best parameters...

**Comment by mforets** [comment]
Alright; i was talking about adding a new `invariant` argument in `validated_integ` that provides a quick path to exit the computation and continue with the other mode in the waiting list if the intersection with the invariant is empty.

I wrote a quick hack in my local TaylorModels, see the diff in:

https://gist.github.com/mforets/8bbb915c14d235e2e4097de29ce20d46

which also needs https://github.com/JuliaReach/Reachability.jl/pull/595

Trying those in this branch, i still get stuck in the first mode (i think its the first mode but i haven't checked, actually):

```julia
julia> include("models/ARCH/NLN/SpacecraftRendezvous/spacecraft_rendezvous.jl")
[ Info: Recompiling stale cache file /Users/forets/.julia/compiled/v1.1/Reachability/CHV4V.ji for Reachability [774a0091-654f-5c65-bbdc-ad5b67b45832]
WARNING: using LazySets.Interval in module TaylorModels conflicts with an existing identifier.
[warn | Reachability]: Several option aliases were used for aliases Symbol[:check_invariant_intersection].
ERROR: LoadError: Error: it cannot prove existence and unicity of the solution:
    t0 = 0.0
    δt = [0, 0.00080936]
    Δ  = [-7.77609e-19, 9.21914e-19] × [-1.54576e-18, 2.37115e-20] × [-9.4927e-16, 1.12757e-15] × [-1.2072e-17, 2.06703e-17] × [0, 0]
    Δx = [-2.73716e-18, 4.89221e-18] × [-9.77053e-21, 6.53935e-16] × [-9.60771e-16, 1.13907e-15] × [-1.90986e-15, 2.92966e-17] × [0, 0]
```

**Comment by lbenet** [comment]
What I am observing is the following: as it is now, the convergence to a remainder `Δx` that satisfies the contraction under Picard iteration is slow in some cases, this one being one, which eventually leads to the error message. 

I was trying to scale such that `Δx = IntervalBox(1.05 .* hull.(Δ, Δx))`, which helps in this problem but this seems too drastic for the other test cases. Maybe we need to readjust the parameters for the other examples.

**Comment by schillic** [comment]
I think for the first location ("approaching") you did not specify a property, so you should not see a difference.

**Comment by lbenet** [comment]
I've been playing with a different approach, and despite being slow, it seems to work. All three modes are coded within the same function (`space_rendezvous!`) for the equations of motion, and include a `switch_controller!` which allows to decide which one applies. 

Using the parameters `orderQ=2`, `orderT=10` and `abs_tolerance=1.0e-28`, and `max_steps=11000` I've been able to reach the end time (`tmax = 200.0`) with `validated_integ` directly. I haven't included any `check_property` function though; for this reason, I am not sure if the problem is properly accomplished or not. I leave it here to keep working on this.

Note that I have commented the equation for the time variation, since it is simply not needed.

Here is the code that is required.
```julia
# Paremeters
const μ = 3.986e14 * 60^2
const r = 42164.0e3
const r2 = r^2
const mc = 500.0
const n2 = μ / r^3
const n = sqrt(n2)

const two_n = 2*n
const μ_r2 = μ/r2

const K₁ = [-28.8287 0.1005 -1449.9754 0.0046;
            -0.087 -33.2562 0.00462 -1451.5013]
const K₂ = [-288.0288 0.1312 -9614.9898 0.0;
            -0.1312 -288.0 0.0 -9614.9883]

const K₁mc = K₁/mc
const K₂mc = K₂/mc

const zK = zero(K₁)

function switch_controller!(t, x)
    bool_time = constant_term(t) < 120.0
    x_coord = constant_term(constant_term(x[1]))
    bool_approach = -100.0 ≥ x_coord ≥ -1000.0
    
    if bool_time
        
        # Approaching mode
        if bool_approach
            return K₁mc * x
        end
        
        # Rendezvous attempt
        return K₂mc * x
    end
    
    # Aborting
    return zK * x
end

# dynamics in the 'approaching' mode
@taylorize function space_rendezvous!(t, x, dx)
    x_1 = r + x[1]
    x_12 = x_1^2
    x_22 = x[2]^2
    rc = sqrt(x_12 + x_22)
    rc3 = rc^3
    μ_rc3 = μ / rc3

    uxy = switch_controller!(t, x)
    
    # x' = vx
    dx[1] = x[3]
    # y' = vy
    dx[2] = x[4]
    # vx' = n²x + 2n*vy + μ/(r^2) - μ/(rc^3)*(r+x) + ux/mc
    dx[3] = (n2*x[1] + two_n*x[4]) + ((μ_r2 - μ_rc3*x_1) + uxy[1])
    # vy' = n²y - 2n*vx - μ/(rc^3)y + uy/mc
    dx[4] = (n2*x[2] - two_n*x[3]) - (μ_rc3*x[2] - uxy[2])
    # t' = 1
    # dx[5] = one(t)

    return dx
end
```

**Comment by lbenet** [comment]
And this is what I get...

space_rendezvous

**Comment by mforets** [comment]
I outsourced the unified code in @lbenet 's [comment](https://github.com/JuliaReach/ReachabilityBenchmarks/pull/129#issuecomment-476436018) to the file `spacecraft_unified.jl`. In my machine it runs in ~570sec. My concern is i'm not convinced that the approach is conservative in the sens that all trajectories that *may* change mode are considered, since the condition necessarily checks a single point, `bool_approach = -100.0 ≥ x_coord ≥ -1000.0`.

Let's merge this and continue in a cleaner branch for further updates.

**Pull request merged**
