### PR TITLE
#21 - SLICOT benchmark script

### LINKED ISSUE #21: Add benchmark script for all SLICOT models
Current plan: (EDIT: outdated)
* Have a big file where all models are represented by a function.
* Each benchmark is represented by a loop over these functions.
  Example: reachability with 1D blocks, `Interval` approximation, and fixed time step

### PR DESCRIPTION
**Pull request by schillic**
Closes #21.

* [x] restructure models
* [x] add benchmarks
  * [x] property checking (discrete, dense)
  * [x] reach 1D one variable
  * [x] reach 1D all variables
  * [x] reach 2D with boxes
  * [x] reach 2D with polygons
* [x] investigate why reach 1D is extremely slow after the first call
* [x] investigate why check 1D dense is extremely slow (is related to passing two parameters; for fixed delta it is fast)
* [x] add optional(!) plotting to reach benchmarks
* [x] remove first three changes from this PR

### CODE REVIEW

**Comment by schillic** [comment]
There is a problem: When I include the model functions (e.g., `motor`), I have to use `Base.invokelatest` to avoid an error in the first call of the function (any further calls will work).
But when I run the function with `Base.invokelatest` a second time, it somehow executes extremely slowly.

**Comment by schillic** [comment]
ready from my side

**Comment by schillic** [comment]
@mforets: I updated the README. Can you check if this is what you meant?

**Comment by mforets** [comment]
> Can you check if this is what you meant?

yes, looks good to me.

**Pull request merged**
