### PR TITLE
use 1D blocks and Interval set type

### PR DESCRIPTION
**Pull request by schillic**
@mforets:
* Do we want to merge this? If yes, what should be the default partition/set type?
* Do we want to have common options for reach and check?

### CODE REVIEW

**Comment by mforets** [comment]
i would prefer that we define more interesting configurations outside the main function,

```julia
...
end # function

compute(...,  :set_type=Interval)..   # using intervals
```

**Comment by schillic** [comment]
I think we should offer a few default combinations in the input options in `Reachability` such as `1D`, `2D` which creates the partition and chooses the set type.

**Comment by mforets** [comment]
Agreed. In the meantime, let me pull out these options and add swap the arguments in the call to `merge(..)` because it is more logical that the given options (`input_options`) overwrite the default ones for this model (`problem_options`).

**Comment by schillic** [comment]
I added an issue [here](https://github.com/JuliaReach/Reachability.jl/issues/114).

**Comment by mforets** [comment]
Once we get [#92 in reachability done](https://github.com/JuliaReach/Reachability.jl/issues/92), we'll be able to remove the `:partition` specification for the `Interval` type given here. Later we will be ready to pull out all those calls to `compute` from benchmark's model files to a `runall.jl` script file. It will collect the data and save it to a table in JSON format.

**Comment by schillic** [comment]
Well done!

**Pull request merged**
