### PR TITLE
WIP - Quadrotor model

### PR DESCRIPTION
**Pull request by mforets**

### CODE REVIEW

**Comment by mforets** [comment]
This model should probably use another symbolic library that can hold the cosine, or directly `TaylorN` for the default `variables` and pass a some extra functions, since sine / cosine functions are not defined for `PolyVar`:

```julia
julia> using DynamicPolynomials

julia> @polyvar x₁
(x₁,)

julia> cos(x₁)
ERROR: MethodError: no method matching cos(::PolyVar{true})

Closest candidates are:
  cos(::BigFloat) at mpfr.jl:736
  cos(::Missing) at math.jl:1070
  cos(::Complex{Float16}) at math.jl:1019
  ...
Stacktrace:
 [1] top-level scope at none:0

julia> using TaylorSeries

julia> TaylorN(1, order=2)
 1.0 x₁ + 𝒪(‖x‖³)

julia> y₁ = TaylorN(1, order=2)
 1.0 x₁ + 𝒪(‖x‖³)

julia> cos(y₁)
 1.0 - 0.5 x₁² + 𝒪(‖x‖³)
```

**Comment by mforets** [comment]
Better rewrite to use `taylorize`, suggested by @lbenet 

```julia
@taylorize function quadrotor!(t, x, dx)
    # parameters of the model
    local g = 9.81           # gravity constant in m/s^2
    local R = 0.1            # radius of center mass in m
    local l = 0.5            # distance of motors to center mass in m
    local Mrotor = 0.1       # motor mass in kg
    local M = 1.0            # center mass in kg
    local m = M + 4*Mrotor   # total mass in kg
    local mg = m*g

    # moments of inertia
    local Jx = (2/5)*M*R^2 + 2*l^2*Mrotor
    local Jy = Jx
    local Jz = (2/5)*M*R^2 + 4*l^2*Mrotor
    local Cyzx = (Jy - Jz)/Jx
    local Czxy = (Jz - Jx)/Jy
    local Cxyz = 0.0 #(Jx - Jy)/Jz

    # unwrap the variables and the controllers; the last three are the controllers
    x₁  = x[1]
    x₂  = x[2]
    x₃  = x[3]
    x₄  = x[4]
    x₅  = x[5]
    x₆  = x[6]
    x₇  = x[7]
    x₈  = x[8]
    x₉  = x[9]
    x₁₀ = x[10]
    x₁₁ = x[11]
    x₁₂ = x[12]
    u₁  = x[13]
    u₂  = x[14]
    u₃  = x[15]

    # equations of the controllers
    F = (mg - 10*(x₃ - u₁)) + 3*x₆  # height control
    τϕ = -(x₇ - u₂) - x₁₀            # roll control
    τθ = -(x₈ - u₃) - x₁₁            # pitch control
    local τψ = 0.0                   # heading is uncontrolled
    #
    Tx = τϕ/Jx
    Ty = τθ/Jy
    Tz = τψ/Jz
    F_m = F/m

    # Some abbreviations
    sx7 = sin(x₇)
    cx7 = cos(x₇)
    sx8 = sin(x₈)
    cx8 = cos(x₈)
    sx9 = sin(x₉)
    cx9 = cos(x₉)
    #
    sx7sx9 = sx7*sx9
    sx7cx9 = sx7*cx9
    cx7sx9 = cx7*sx9
    cx7cx9 = cx7*cx9
    sx7cx8 = sx7*cx8
    cx7cx8 = cx7*cx8
    sx7_cx8 = sx7/cx8
    cx7_cx8 = cx7/cx8
    #
    x4cx8 = cx8*x₄
    #
    p11 = sx7_cx8*x₁₁
    p12 = cx7_cx8*x₁₂
    xdot9 = p11 + p12

    # differential equations for the quadrotor
#     ẋ₁ = cos(x₈)*cos(x₉)*x₄ + (sin(x₇)*sin(x₈)*cos(x₉) - cos(x₇)*sin(x₉))*x₅
#          + (cos(x₇)*sin(x₈)*cos(x₉) + sin(x₇)*sin(x₉))*x₆
#     ẋ₂ = cos(x₈)*sin(x₉)*x₄ + (sin(x₇)*sin(x₈)*sin(x₉) + cos(x₇)*cos(x₉))*x₅
#          + (cos(x₇)*sin(x₈)*sin(x₉) - sin(x₇)*cos(x₉))*x₆
#     ẋ₃ = sin(x₈)*x₄ - sin(x₇)*cos(x₈)*x₅ - cos(x₇)*cos(x₈)*x₆
#     ẋ₄ = x₁₂*x₅ - x₁₁*x₆ - g*sin(x₈)
#     ẋ₅ = x₁₀*x₆ - x₁₂*x₄ + g*cos(x₈)*sin(x₇)
#     ẋ₆ = x₁₁*x₄ - x₁₀*x₅ + g*cos(x₈)*cos(x₇) - F/m
#     ẋ₇ = x₁₀ + sin(x₇)*tan(x₈)*x₁₁ + cos(x₇)*tan(x₈)*x₁₂
#     ẋ₈ = cos(x₇)*x₁₁ - sin(x₇)*x₁₂
#     ẋ₉ = (sin(x₇)/cos(x₈))*x₁₁ + (cos(x₇)/cos(x₈))*x₁₂
#     ẋ₁₀ = (Jy - Jz)/Jx * x₁₁ * x₁₂ + τϕ/Jx
#     ẋ₁₁ = (Jz - Jx)/Jy * x₁₀ * x₁₂ + τθ/Jy
#     ẋ₁₂ = (Jx - Jy)/Jz * x₁₀ * x₁₁ + τψ/Jz
    #
    dx[1] = (cx9*x4cx8 + (sx7cx9*sx8 - cx7sx9)*x₅) + (cx7cx9*sx8 + sx7sx9)*x₆
    dx[2] = (sx9*x4cx8 + (sx7sx9*sx8 + cx7cx9)*x₅) + (cx7sx9*sx8 - sx7cx9)*x₆
    dx[3] = (sx8*x₄ - sx7cx8*x₅) - cx7cx8*x₆
    dx[4] = (x₁₂*x₅ - x₁₁*x₆) - g*sx8
    dx[5] = (x₁₀*x₆ - x₁₂*x₄) + g*sx7cx8
    dx[6] = (x₁₁*x₄ - x₁₀*x₅) + (g*cx7cx8 - F_m)
    dx[7] = x₁₀ + sx8*xdot9
    dx[8] = cx7*x₁₁ - sx7*x₁₂
    dx[9] = xdot9
    dx[10] = Cyzx * (x₁₁ * x₁₂) + Tx
    dx[11] = Czxy * (x₁₀ * x₁₂) + Ty
    dx[12] = Cxyz * (x₁₀ * x₁₁) + Tz
    dx[13] = zero(x[13])
    dx[14] = zero(x[14])
    dx[15] = zero(x[15])
    #
    return dx
end

```

**Comment by lbenet** [comment]
With the last commits in https://github.com/JuliaIntervals/TaylorModels.jl/pull/18, this problem can be solved. The parameters I have used are: 
```julia
const abs_tol = 1.0e-12
const orderT=12
const orderQ=2
```
I haven't checked if these can be optimized further; in my computer the problem is solved in about ~42 sec.

The `check_property` function is:
```julia
function check_property(t, x)
    b1 = (x[3] < 1.4)
    b2 = t ≥ 1.0 ? (x[3] > 0.9) : true
    b3 = t ≥ 5.0 ? (0.98 ≤ x[3] ≤ 1.02) : true
    return b1 && b2 && b3
end
```
(We may probably omit everything related to `b3` in the above function.)

Note that now `check_property` *requires* now two arguments; this affects the definitions used in #66 and #67, which are outdated.

**Comment by lbenet** [comment]
CC @dpsanders

**Comment by mforets** [comment]
Very good 👍  I'm updating the model to update this branch.

> (We may probably omit everything related to b3 in the above function.)

Why? Take `x[3] = 0.95` for all times. It satisfies `b1` and `b2` but not `b3`.

**Comment by lbenet** [comment]
> Take x[3] = 0.95 for all times. It satisfies b1 and b2 but not b3.

I was thinking about omitting it because it is defined precisely at the end time of the integration, so it only matter for the very last point...

**Comment by mforets** [comment]
Ok, i see now 😄 given that the time horizon is 5 seconds.

**Comment by lbenet** [comment]
Incidentally, I also played with the equations using the control parameters as such, i.e., as parameters inside the function `quadrotor!`. Everything works fine and yields some small speed-up.

**Comment by mforets** [comment]
Ok, so do you suggest to use `u₁, u₂, u₃` as in [this function](https://github.com/JuliaReach/ReachabilityBenchmarks/pull/70#issuecomment-469510674), or to write them as constant parameters as in [this function](https://github.com/JuliaReach/ReachabilityBenchmarks/pull/70/files#diff-a7625605497e0e1d6b108377266251faR29)?

**Comment by lbenet** [comment]
What i used is the following function

```julia
@taylorize function quadrotor2!(t, x, dx)
    # parameters of the model
    local g = 9.81           # gravity constant in m/s^2
    local R = 0.1            # radius of center mass in m
    local l = 0.5            # distance of motors to center mass in m
    local Mrotor = 0.1       # motor mass in kg
    local M = 1.0            # center mass in kg
    local m = M + 4*Mrotor   # total mass in kg
    local mg = m*g

    # moments of inertia
    local Jx = (2/5)*M*R^2 + 2*l^2*Mrotor
    local Jy = Jx
    local Jz = (2/5)*M*R^2 + 4*l^2*Mrotor
    local Cyzx = (Jy - Jz)/Jx
    local Czxy = (Jz - Jx)/Jy
    local Cxyz = 0.0 #(Jx - Jy)/Jz

    # Control parameters
    local u₁ = 1.0
    local u₂ = 0.0
    local u₃ = 0.0

    # unwrap the variables and the controllers; the last three are the controllers
    x₁  = x[1]
    x₂  = x[2]
    x₃  = x[3]
    x₄  = x[4]
    x₅  = x[5]
    x₆  = x[6]
    x₇  = x[7]
    x₈  = x[8]
    x₉  = x[9]
    x₁₀ = x[10]
    x₁₁ = x[11]
    x₁₂ = x[12]

    # equations of the controllers
    F = (mg - 10*(x₃ - u₁)) + 3*x₆  # height control
    τϕ = -(x₇ - u₂) - x₁₀            # roll control
    τθ = -(x₈ - u₃) - x₁₁            # pitch control
    local τψ = 0.0                   # heading is uncontrolled
    #
    Tx = τϕ/Jx
    Ty = τθ/Jy
    Tz = τψ/Jz
    F_m = F/m

    # Some abbreviations
    sx7 = sin(x₇)
    cx7 = cos(x₇)
    sx8 = sin(x₈)
    cx8 = cos(x₈)
    sx9 = sin(x₉)
    cx9 = cos(x₉)
    #
    sx7sx9 = sx7*sx9
    sx7cx9 = sx7*cx9
    cx7sx9 = cx7*sx9
    cx7cx9 = cx7*cx9
    sx7cx8 = sx7*cx8
    cx7cx8 = cx7*cx8
    sx7_cx8 = sx7/cx8
    cx7_cx8 = cx7/cx8    
    #
    x4cx8 = cx8*x₄
    #
    p11 = sx7_cx8*x₁₁
    p12 = cx7_cx8*x₁₂
    xdot9 = p11 + p12

    # differential equations for the quadrotor
    #    
    dx[1] = (cx9*x4cx8 + (sx7cx9*sx8 - cx7sx9)*x₅) + (cx7cx9*sx8 + sx7sx9)*x₆
    dx[2] = (sx9*x4cx8 + (sx7sx9*sx8 + cx7cx9)*x₅) + (cx7sx9*sx8 - sx7cx9)*x₆
    dx[3] = (sx8*x₄ - sx7cx8*x₅) - cx7cx8*x₆
    dx[4] = (x₁₂*x₅ - x₁₁*x₆) - g*sx8
    dx[5] = (x₁₀*x₆ - x₁₂*x₄) + g*sx7cx8
    dx[6] = (x₁₁*x₄ - x₁₀*x₅) + (g*cx7cx8 - F_m)
    dx[7] = x₁₀ + sx8*xdot9
    dx[8] = cx7*x₁₁ - sx7*x₁₂
    dx[9] = xdot9
    dx[10] = Cyzx * (x₁₁ * x₁₂) + Tx
    dx[11] = Czxy * (x₁₀ * x₁₂) + Ty
    dx[12] = Cxyz * (x₁₀ * x₁₁) + Tz
     #
    return dx
end
```

Some comments with regards to the [second function](https://github.com/JuliaReach/ReachabilityBenchmarks/pull/70/files#diff-a7625605497e0e1d6b108377266251faR29) mentioned above: 

- It's ok to have `u₁`, `u₂` and `u₃` (or other parameters) as external constants; if they are used inside the function is better (for `@taylorize`) to declare them as `local`.
- I don't think that unwrapping a vector works together with `@taylorize`, which is why I did it above by hand. (But please try to see if it works as expected!)
- `@taylorize` works *better* if any function calls are unary or binary, so with one or two arguments. That is the reason I indroduced whatever (ugly named) shortcuts and also parenthesis.

All this is due to the very primitive implementation of `@taylorize`...

**Comment by mforets** [comment]
Sure. I was thinking that we can avoid the recomputations of the moments of intertia etc each time that `quadrotor!` is called. Or this is actually achieved with the `local` annotation?

**Comment by lbenet** [comment]
Your approach for keeping those parameters as `const` is quite fine, and I guess better than using them inside the function as `local`. What I am not sure that works is unwrapping the vectors.

**Pull request merged**
